/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: passenger.proto
 *
 */

/*
 * Copyright 2017, gRPC Authors All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import Foundation
import Dispatch
import gRPC

/// Type for errors thrown from generated client code.
internal enum Io_Moia_PassengerClientError : Error {
  case endOfStream
  case invalidMessageReceived
  case error(c: CallResult)
}

/// BookTrip (Unary)
internal class Io_Moia_PassengerBookTripCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/io.moia.Passenger/BookTrip")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Io_Moia_BookingRequest,
                       metadata: Metadata) throws -> Io_Moia_BookingResponse {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Io_Moia_BookingResponse?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Io_Moia_PassengerClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Io_Moia_BookingRequest,
                         metadata: Metadata,
                         completion: @escaping (Io_Moia_BookingResponse?, CallResult)->())
    throws -> Io_Moia_PassengerBookTripCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Io_Moia_BookingResponse(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// TrackVehicle (Server Streaming)
internal class Io_Moia_PassengerTrackVehicleCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/io.moia.Passenger/TrackVehicle")
  }

  /// Call this once with the message to send. Nonblocking.
  fileprivate func start(request: Io_Moia_LocationRequest,
                         metadata: Metadata,
                         completion: @escaping (CallResult) -> ())
    throws -> Io_Moia_PassengerTrackVehicleCall {
      let requestData = try request.serializedData()
      try call.start(.serverStreaming,
                     metadata:metadata,
                     message:requestData,
                     completion:completion)
      return self
  }

  /// Call this to wait for a result. Blocking.
  internal func receive() throws -> Io_Moia_Location {
    var returnError : Io_Moia_PassengerClientError?
    var returnResponse : Io_Moia_Location!
    let sem = DispatchSemaphore(value: 0)
    do {
      try receive() {response, error in
        returnResponse = response
        returnError = error
        sem.signal()
      }
      _ = sem.wait(timeout: DispatchTime.distantFuture)
    }
    if let returnError = returnError {
      throw returnError
    }
    return returnResponse
  }

  /// Call this to wait for a result. Nonblocking.
  internal func receive(completion:@escaping (Io_Moia_Location?, Io_Moia_PassengerClientError?)->()) throws {
    do {
      try call.receiveMessage() {(responseData) in
        if let responseData = responseData {
          if let response = try? Io_Moia_Location(serializedData:responseData) {
            completion(response, nil)
          } else {
            completion(nil, Io_Moia_PassengerClientError.invalidMessageReceived)
          }
        } else {
          completion(nil, Io_Moia_PassengerClientError.endOfStream)
        }
      }
    }
  }
}

/// Echo (Bidirectional Streaming)
internal class Io_Moia_PassengerEchoCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/io.moia.Passenger/Echo")
  }

  /// Call this to start a call. Nonblocking.
  fileprivate func start(metadata:Metadata, completion:@escaping (CallResult)->())
    throws -> Io_Moia_PassengerEchoCall {
      try self.call.start(.bidiStreaming, metadata:metadata, completion:completion)
      return self
  }

  /// Call this to wait for a result. Blocking.
  internal func receive() throws -> Io_Moia_Pong {
    var returnError : Io_Moia_PassengerClientError?
    var returnMessage : Io_Moia_Pong!
    let sem = DispatchSemaphore(value: 0)
    do {
      try receive() {response, error in
        returnMessage = response
        returnError = error
        sem.signal()
      }
      _ = sem.wait(timeout: DispatchTime.distantFuture)
    }
    if let returnError = returnError {
      throw returnError
    }
    return returnMessage
  }

  /// Call this to wait for a result. Nonblocking.
  internal func receive(completion:@escaping (Io_Moia_Pong?, Io_Moia_PassengerClientError?)->()) throws {
    do {
      try call.receiveMessage() {(data) in
        if let data = data {
          if let returnMessage = try? Io_Moia_Pong(serializedData:data) {
            completion(returnMessage, nil)
          } else {
            completion(nil, Io_Moia_PassengerClientError.invalidMessageReceived)
          }
        } else {
          completion(nil, Io_Moia_PassengerClientError.endOfStream)
        }
      }
    }
  }

  /// Call this to send each message in the request stream.
  internal func send(_ message:Io_Moia_Ping, errorHandler:@escaping (Error)->()) throws {
    let messageData = try message.serializedData()
    try call.sendMessage(data:messageData, errorHandler:errorHandler)
  }

  /// Call this to close the sending connection. Blocking.
  internal func closeSend() throws {
    let sem = DispatchSemaphore(value: 0)
    try closeSend() {
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
  }

  /// Call this to close the sending connection. Nonblocking.
  internal func closeSend(completion:@escaping ()->()) throws {
    try call.close() {
      completion()
    }
  }
}

/// Call methods of this class to make API calls.
internal class Io_Moia_PassengerService {
  private var channel: Channel

  /// This metadata will be sent with all requests.
  internal var metadata : Metadata

  /// This property allows the service host name to be overridden.
  /// For example, it can be used to make calls to "localhost:8080"
  /// appear to be to "example.com".
  internal var host : String {
    get {
      return self.channel.host
    }
    set {
      self.channel.host = newValue
    }
  }

  /// Create a client that makes insecure connections.
  internal init(address: String) {
    gRPC.initialize()
    channel = Channel(address:address)
    metadata = Metadata()
  }

  /// Create a client that makes secure connections.
  internal init(address: String, certificates: String?, host: String?) {
    gRPC.initialize()
    channel = Channel(address:address, certificates:certificates, host:host)
    metadata = Metadata()
  }

  /// Synchronous. Unary.
  internal func booktrip(_ request: Io_Moia_BookingRequest)
    throws
    -> Io_Moia_BookingResponse {
      return try Io_Moia_PassengerBookTripCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func booktrip(_ request: Io_Moia_BookingRequest,
                  completion: @escaping (Io_Moia_BookingResponse?, CallResult)->())
    throws
    -> Io_Moia_PassengerBookTripCall {
      return try Io_Moia_PassengerBookTripCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func trackvehicle(_ request: Io_Moia_LocationRequest, completion: @escaping (CallResult)->())
    throws
    -> Io_Moia_PassengerTrackVehicleCall {
      return try Io_Moia_PassengerTrackVehicleCall(channel).start(request:request, metadata:metadata, completion:completion)
  }
  /// Asynchronous. Bidirectional-streaming.
  /// Use methods on the returned object to stream messages,
  /// to wait for replies, and to close the connection.
  internal func echo(completion: @escaping (CallResult)->())
    throws
    -> Io_Moia_PassengerEchoCall {
      return try Io_Moia_PassengerEchoCall(channel).start(metadata:metadata, completion:completion)
  }
}
